# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: my-app
    - run: npm run build --if-present
      working-directory: my-app
    - run: npm test
      working-directory: my-app
    - name: Deploy
      run: |
        git config --global user.name Affan-dorid
        git config --global user.name u2017230@giki.edu.pk
        git remote set-url origin https://github.com/Affan-droid/Assignment_2
        npm run deploy
      env: 
        user_name: 'Affan-dorid' 
        user_email: 'u2017230@giki.edu.pk' 
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }} 
        repository:  https://github.com/Affan-droid/Assignment_2  
